project:
  type: website
  output-dir: docs

# Meta
description-meta: "Quarto Academic Website Template adapted by Zhiqing Ma"
author-meta: "Zhiqing Ma"

website:
  title: "Zhiqing Ma"
  # image: "https://quarto.org/quarto.png"
  description: "Quarto Academic Website Template adapted by Zhiqing Ma"
 
  navbar:
    background: light # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      # - text: About
      #   menu:
      #     - text: News
      #       href: posts.qmd#category=news
      #     - text: Events
      #       href: posts.qmd#category=event      
      #     - text: Contact
      #       href: contact.qmd       
      - text: Contact
        href: contact.qmd          
      - text: Research
        href: projects.qmd                                
      - text: Interns # Comment the Teaching part out to remove the Teaching page
        href: interns.qmd
      - text: Interests
        menu:        
        - text: Roller Skating
          href: posts/interests/skating.html#category=skating     
        - text: Running
          href: posts/interests/running.html#category=running          
      # - text: Group   # Comment the Group part out to remove the Group page
      #   href: people.qmd

    right: 
      # - text: CV
      #   href: files/nsf-biosketch.pdf
      - icon: github
        href: https://github.com/mk1777-z
        target: _blank
      # - text: "{{< fa brands bluesky >}}"
      #   href: https://bsky.app
      #   target: _blank      
      - icon: rss
        href: posts.xml
        target: _blank
  
  page-navigation: true
  
  page-footer: 
    left: "[Zhiqing Ma](https://github.com/mk1777-z) &copy; <script>document.write(new Date().getFullYear())</script>" 
    center: "Always be curious about the world"
    right:  
      - icon: github
        href: https://github.com/mk1777-ze
        target: _blank
      - icon: rss
        href: posts.xml
        target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  repo-url: https://github.com/mk1777-z/zhiqingma.github.io
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://drganghe.github.io/quarto-academic-website-template"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

